title = "My Awesome Blog"
subtitle = "It's like Dropbox, for thoughts."
author = "Author Name"
linkPrefix = "/gatsby-starter-blog-bulma"
github = "https://github.com/gatsbyjs/gatsby"
twitter = "https://twitter.com/gatsbyjs"
facebook = ""
googleplus = ""
linkedin = ""
